include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.mocks.dart'
    - '**/*.config.dart'

linter:
  rules:
    - always_declare_return_types
    - avoid_annotating_with_dynamic
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_void_async
    - cascade_invocations
    - curly_braces_in_flow_control_structures
    - empty_catches
    - file_names
    - empty_statements
    - implementation_imports
    - library_names
    - overridden_fields
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_foreach
    - prefer_single_quotes
    - prefer_relative_imports
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_this
